version: "2.1"

services:
  app:
    image: opencpu/base:latest
    restart: always
    expose:
      - 80
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.wiki.frontend.rule=Host: ${HOST_URL}"
      - "traefik.wiki.port=80"
      - "traefik.wiki.protocol=http"
    networks:
      - web
      - default

networks:
  web:
    external: true
